name: twin7
on:
  workflow_dispatch:
    inputs:
      auth:
        description: Imput you NGROK AUTH
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download windows files
      run: wget -O w7x64.img https://bit.ly/akuhnetw7X64
    - name: apt update
      run: apt-get update -y
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > /dev/null 2>&1
    - name: unzip ngrock
      run: unzip ngrok-stable-linux-amd64.zip > /dev/null 2>&1
    - name: active
      run: ./ngrok authtoken ${{ github.event.inputs.auth }}
    - name: nohup
      run: nohup ./ngrok tcp 3388 &>/dev/null &
    - name: qemu
      run: apt-get install qemu-system-x86 -y
    - name: Starting
      run: qemu-system-x86_64 -hda w7x64.img -m 4G -smp cores=4 -net user,hostfwd=tcp::3388-:3389 -net nic -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0 -vga vmware -nographic &>/dev/null &
    - name: RDP Address
      run: curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'
    - name: Keep Alive
      run: sleep 21600
